site_name: Ryan's Notes
site_url: https://sitename.example
theme:
  name: material
  icon:
    logo: fontawesome/solid/r
  features:
    - navigation.footer
    - navigation.expand

  #for toggleable settings
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange    


markdown_extensions:
  - tables
   #Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Content Tabls
  - pymdownx.tabbed:
      alternate_style: true

  # Callouts aka admonitions
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
        
  
extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
#extra:
#  social:
#    - icon: simple/youtube
#      link: https://youtube.com/@james-willett
#    - icon: simple/linkedin
#      link: https://linkedin.com/in/willettjames 

copyright: Copyright &copy; 2024 James Willett  